#!/usr/bin/env python3
"""PF5 projected-clause relation-forest signature cap probe v12.3.

Post-hoc only on already-observed seed 908001.  This probes a polynomial,
assignment-independent upper bound on PS signature count built from certified
binary relations among distinct nonempty projected clauses.

For projected clauses A,B with satisfaction bits s_A,s_B:
  * A subseteq B => (1,0) is impossible;
  * B subseteq A => (0,1) is impossible;
  * A union B tautological => (0,0) is impossible;
  * complementary unit clauses => (1,1) is impossible.

Any signature generated by an assignment obeys all these relations.  We select
a deterministic acyclic subset (strongest edges first) and count its satisfying
bit patterns exactly by tree DP.  Ignoring remaining constraints can only make
the count larger, so the result is a sound upper bound.  The feature is source-
only and polynomial; the exact PS scorer is used only afterwards for this
post-hoc diagnostic.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import sys
from pathlib import Path

import pf5_slime_pswidth_blind_probe_v9 as v9
import pf5_slime_exact_optimality_gap_v11 as v11

SEED = 908001
VARIABLE_COUNT = 5
CLAUSE_COUNT = 7


def import_producer(path: Path):
    spec = importlib.util.spec_from_file_location("slime_v2_relation_probe_pin", path)
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load producer")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    except Exception:
        sys.modules.pop(spec.name, None)
        raise
    return module


def distinct_projected(formula, clause_indices, visible_variables):
    values = set()
    for index in sorted(clause_indices):
        projected = frozenset(
            lit for lit in formula[index] if abs(lit) in visible_variables
        )
        if projected:
            values.add(projected)
    return sorted(values, key=lambda c: (len(c), tuple(sorted(c))))


def allowed_pairs(a, b):
    allowed = {(0,0),(0,1),(1,0),(1,1)}
    reasons = []
    if a <= b:
        allowed.discard((1,0))
        reasons.append("A_SUBSET_B_FORBIDS_10")
    if b <= a:
        allowed.discard((0,1))
        reasons.append("B_SUBSET_A_FORBIDS_01")
    union = set(a) | set(b)
    if any(-lit in union for lit in union):
        allowed.discard((0,0))
        reasons.append("A_OR_B_TAUTOLOGY_FORBIDS_00")
    if len(a)==1 and len(b)==1:
        la = next(iter(a)); lb = next(iter(b))
        if la == -lb:
            allowed.discard((1,1))
            reasons.append("COMPLEMENTARY_UNITS_FORBID_11")
    return tuple(sorted(allowed)), reasons


class DSU:
    def __init__(self,n):
        self.p=list(range(n))
    def find(self,x):
        while self.p[x]!=x:
            self.p[x]=self.p[self.p[x]]; x=self.p[x]
        return x
    def union(self,a,b):
        a=self.find(a); b=self.find(b)
        if a==b: return False
        if a>b: a,b=b,a
        self.p[b]=a
        return True


def relation_forest(clauses):
    edges=[]
    for i in range(len(clauses)):
        for j in range(i+1,len(clauses)):
            allowed,reasons=allowed_pairs(clauses[i],clauses[j])
            if len(allowed)<4:
                edges.append((len(allowed), i, j, allowed, reasons))
    edges.sort(key=lambda row:(row[0], row[1], row[2]))
    dsu=DSU(len(clauses))
    selected=[]
    for strength,i,j,allowed,reasons in edges:
        if dsu.union(i,j):
            selected.append({
                "i":i,"j":j,"allowed":[list(x) for x in allowed],
                "reasons":reasons,"allowed_pair_count":strength,
            })
    return selected


def count_forest_patterns(node_count, edges):
    if node_count==0:
        return 1
    adjacency=[[] for _ in range(node_count)]
    for e in edges:
        allowed={tuple(x) for x in e["allowed"]}
        i=e["i"]; j=e["j"]
        adjacency[i].append((j,allowed,False))
        adjacency[j].append((i,allowed,True))
    seen=set(); total=1
    for root in range(node_count):
        if root in seen: continue
        parent={root:-1}; pedge={}; order=[root]; seen.add(root)
        for node in order:
            for nxt,allowed,reversed_dir in adjacency[node]:
                if nxt in parent: continue
                parent[nxt]=node; pedge[nxt]=(allowed,reversed_dir); order.append(nxt); seen.add(nxt)
        dp={}
        for node in reversed(order):
            counts=[1,1]
            for child,par in parent.items():
                if par!=node: continue
                allowed,reversed_dir=pedge[child]
                new=[]
                for pval in (0,1):
                    subtotal=0
                    for cval in (0,1):
                        pair=(cval,pval) if reversed_dir else (pval,cval)
                        if pair in allowed:
                            subtotal += dp[child][cval]
                    new.append(counts[pval]*subtotal)
                counts=new
            dp[node]=counts
        total *= dp[root][0]+dp[root][1]
    return total


def side_cap(formula, clause_indices, visible_variables):
    clauses=distinct_projected(formula, clause_indices, visible_variables)
    forest=relation_forest(clauses)
    forest_patterns=count_forest_patterns(len(clauses),forest)
    assignment_bound=1<<len(visible_variables)
    return {
        "distinct_projected_clauses":[sorted(c,key=lambda x:(abs(x),x<0)) for c in clauses],
        "relation_forest":forest,
        "forest_pattern_bound":forest_patterns,
        "assignment_bound":assignment_bound,
        "certified_signature_cap":min(assignment_bound,forest_patterns),
    }


def relation_forest_cap(formula, selected_leaves):
    all_clauses=set(range(len(formula)))
    all_vars={abs(l) for c in formula for l in c}
    selected_vars={int(x.split(':',1)[1]) for x in selected_leaves if x.startswith('v:')}
    selected_clauses={int(x.split(':',1)[1]) for x in selected_leaves if x.startswith('c:')}
    right_vars=all_vars-selected_vars
    left=side_cap(formula,all_clauses-selected_clauses,selected_vars)
    right=side_cap(formula,selected_clauses,right_vars)
    return {"left":left,"right":right,"combined_cap":max(left["certified_signature_cap"],right["certified_signature_cap"])}


def run(producer, producer_identity):
    formula=v9.random_connected_3cnf(SEED,VARIABLE_COUNT,CLAUSE_COUNT)
    router=producer.SlimeSignatureCapCandidateRouter()
    manifest=router.generate_manifest(formula)
    order=next(c.linear_leaf_order for c in manifest.candidates if c.name=='SLIME_SIGNATURE_CAP_PRESSURE')
    leaves=sorted(order); index={leaf:i for i,leaf in enumerate(leaves)}
    cut_values,ledger=v11.exact_cut_cache(formula,leaves)
    prefix=set(order[:3])
    rows=[]
    for leaf in sorted(set(leaves)-prefix):
        trial=prefix|{leaf}; mask=0
        for x in trial: mask |= 1<<index[x]
        cap=relation_forest_cap(formula,trial)
        rows.append({"leaf":leaf,"relation_forest_cap":cap,"exact_next_ps":cut_values[mask]})
    chosen=next(r for r in rows if r['leaf']==order[3])
    best=min(r['relation_forest_cap']['combined_cap'] for r in rows)
    best_rows=[r for r in rows if r['relation_forest_cap']['combined_cap']==best]
    exact_best=min(r['exact_next_ps'] for r in rows)
    helpful=any(r['exact_next_ps']<chosen['exact_next_ps'] and r['relation_forest_cap']['combined_cap']<chosen['relation_forest_cap']['combined_cap'] for r in rows)
    result={
        "artifact_id":"PF5-PROJECTED-RELATION-FOREST-CAP-PROBE-V12.3",
        "status":"POSTHOC_THEOREM_FEATURE_PROBE_COMPLETE",
        "seed":SEED,
        "posthoc_not_holdout":True,
        "producer":producer_identity,
        "prefix_before_gap":order[:3],
        "v2_chosen_next":order[3],
        "candidate_rows":rows,
        "chosen_row":chosen,
        "relation_forest_best_cap":best,
        "relation_forest_best_rows":best_rows,
        "exact_best_next_ps":exact_best,
        "relation_forest_breaks_observed_v2_tie_in_helpful_direction":helpful,
        "theorem":{
            "subset_implication":True,
            "tautological_pair_exhaustiveness":True,
            "complementary_unit_exclusion":True,
            "acyclic_relation_subset_counted_by_tree_dp":True,
            "ignoring_unselected_sound_constraints_only_loosens_bound":True,
            "source_only":True,
            "polynomial_feature_construction":True,
        },
        "exact_verifier_ledger":ledger,
        "p_vs_np":"OPEN",
    }
    payload=json.dumps(result,sort_keys=True,separators=(',',':')).encode()
    result['result_sha256']=hashlib.sha256(payload).hexdigest()
    return result


def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--producer-path',type=Path,required=True); ap.add_argument('--json-out',type=Path); args=ap.parse_args()
    raw=args.producer_path.read_bytes(); producer=import_producer(args.producer_path)
    result=run(producer,{"path":str(args.producer_path),"file_sha256":hashlib.sha256(raw).hexdigest(),"role":"PINNED_V2_POSTHOC_RELATION_FEATURE_PROBE"})
    if args.json_out: args.json_out.write_text(json.dumps(result,indent=2,sort_keys=True),encoding='utf-8')
    print('PF5_PROJECTED_RELATION_FOREST_CAP_PROBE_V12_3 =',result['status'])
    print('PREFIX =',result['prefix_before_gap'],'V2_CHOSEN =',result['v2_chosen_next'])
    for r in result['candidate_rows']:
        print(r['leaf'],'FOREST=',r['relation_forest_cap']['combined_cap'],'EXACT=',r['exact_next_ps'])
    print('RELATION_FOREST_BREAKS_TIE_HELPFULLY =',result['relation_forest_breaks_observed_v2_tie_in_helpful_direction'])
    print('P_VS_NP = OPEN'); print('RESULT_SHA256 =',result['result_sha256'])

if __name__=='__main__': main()
